apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  {{- if (or (.Values.annotations.service) (eq .Values.chartMode "aws")) }}
  annotations:
    {{- if .Values.annotations.service }}
      {{- toYaml .Values.annotations.service | nindent 4 }}
    {{- end }}
    {{- if eq .Values.chartMode "aws" }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    {{- end }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: 3080
    protocol: TCP
  - name: sshproxy
    port: 3023
    targetPort: 3023
    protocol: TCP
  - name: k8s
    port: 3026
    targetPort: 3026
    protocol: TCP
  - name: sshtun
    port: 3024
    targetPort: 3024
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
