apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBindingName | default .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterRoleName | default .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
