apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.annotations.serviceAccount }}
  annotations:
{{- toYaml .Values.annotations.serviceAccount | nindent 4 }}
{{- end -}}